config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :spectacles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spectacle.rb
class Spectacle < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :spectacles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		@spectacles = Spectacle.order(id: :desc)
  						   	   .where user_id: current_user.id	
  	end
  end
end

app/controllers/spectacles_controller.rb
class SpectaclesController < ApplicationController
	
	before_action :set_spectacle, only: [:show, :edit, :update, :destroy]

	def index
		@spectacles = Spectacle.where user_id: current_user.id
	end

	def new
		@spectacle = Spectacle.new
	end

	def create
		# render plain: params[:spectacle].inspect --Trae las variables de la vista
		@spectacle = current_user.spectacles.new(spectacle_params)
		@spectacle.save
		redirect_to @spectacle
	end

	def show
	end

	def edit
	end

	def update
		@spectacle.update spectacle_params
		redirect_to @spectacle
	end

	def destroy
		@spectacle.destroy
		redirect_to spectacles_path
	end

	private
	def spectacle_params
		params.require(:spectacle).permit(:name, :category, :place, :address, 
			:date_start, :date_finish, :type_event, :email_user)
	end

	def set_spectacle 
		@spectacle = Spectacle.find params[:id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/spectacles_helper.rb
module SpectaclesHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
		<div class="row">
			<div class="col-12">
				<h1>Bienvenido  <%= current_user.email %> </h1>
				<div>
					<ul class="nav">
						<li>
							<p><strong>Tienes <%= @spectacles.count %></strong> Eventos</p>
							<%= link_to 'Crear Nuevo Evento', new_spectacle_path %>
						</li>
					</ul>
				</div>		
			</div>
		</div>
		<div class="row">
			<%= render @spectacles %>		
		</div>
		<% else %>
		<div class="index">
			<h1>Bienvenido a su gestor de Eventos</h1>		
		</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <a href="https://www.uniandes.edu.co">
        <img src="https://uniandes.edu.co/sites/default/files/logo-header_0_0.png" alt="" heigth="60px">
      </a>
      <div class="header-right">
        <nav>
          <ul class="nav justify-content-end">
            <%- if user_signed_in?%>
              <li class="nav-item">
                <%= link_to 'Salir', destroy_user_session_path, method: :delete %>
              </li>
              <li class="nav-item">
                <%= link_to 'Principal', :controller => "home"%>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to ' Iniciar ', new_user_session_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to ' Registrarme ', new_user_registration_path, class: "nav-link" %>
              </li>
            <%end%>
          </ul>
        </nav>
      </div>
    </header>

    <div class="container">
      <div class="row  h-100 justify-content-center align-items-center">
        <div class="col-md-9"> 
          
          <div class="container">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <%= yield %>  
          </div>
        </div>
        <br> 
      </div>  
    </div> 
  </body>
</html>

app/views/spectacles/_form.html.erb
	<div class="form-group">
		<%= form_for @spectacle do |f| %>
			<%= f.label :Nombre %>
			<%= f.text_field :name, class:'form-control' %><br>
			<%= f.label :Categoria %>
			<%= f.text_field :category, class:'form-control' %><br>
			<%= f.label :Lugar %>
			<%= f.text_field :place, class:'form-control' %><br>
			<%= f.label :Direccion %>
			<%= f.text_field :address, class:'form-control' %><br>
			<%= f.label :Fecha_de_Inicio %>
			<%= f.text_field :date_start, class:'form-control' %><br>
			<%= f.label :Fecha_Final %>
			<%= f.text_field :date_finish, class:'form-control' %><br>
			<%= f.label :Tipo %>
			<%= f.text_field :type_event, class:'form-control'%><br>
			<%= f.label :Email %>
			<%= f.text_field :email_user, class:'form-control'%><br>
			<%= f.submit 'Enviar', class:'btn btn-primary'%>
		<% end %> 	
	</div>

app/views/spectacles/_spectacle.html.erb
<div class="col">
	<figure class="figure">
		<img src="https://cdn3.iconfinder.com/data/icons/round-icons-vol-2/512/Ticket-512.png" class="figure-img img-fluid rounded" alt="Imagen del evento">
		<figcaption class="figure-caption">
			<%= spectacle.name %>
			<%= link_to 'Ver ', spectacle_path(spectacle.id) %> 
			<%= link_to 'Editar ', edit_spectacle_path(spectacle) %> 
			<%= link_to 'Borrar ', spectacle, method: :delete, data: {confirm: 'Esta seguro de eliminar el evento?'} %>			
		</figcaption>
	</figure>
</div>

app/views/spectacles/edit.html.erb
<div class="container">
	<p>Editar Evento</p>
	<%= render 'form' %>	
</div>

app/views/spectacles/index.html.erb
<div class="container">
	<div class="row">
		<%= render @spectacles %>		
	</div>
</div>

	

app/views/spectacles/new.html.erb
<div class="container">
	<p>Nuevo Evento</p>
	<%= render 'form'%>	
</div>

app/views/spectacles/show.html.erb
<div class="index">
	<h1>Detalle del Evento</h1>	
</div>


<div class="container">
	<table class="table table-responsive table-hover">
		<thead>
			<tr>
				<th scope="col">Nombre</th>
				<th scope="col">Categoria</th>
				<th scope="col">Lugar</th>
				<th scope="col">Dirección</th>
				<th scope="col">Fecha de Inicio</th>
				<th scope="col">Fecha Final</th>
				<th scope="col">Tipo de Evento</th>
			</tr>

		</thead>
		<tbody>
			<tr>
				<td><%= @spectacle.name %></td>	
				<td>
					<%= @spectacle.category %>
				</td>
				<td>
					<%= @spectacle.place %>
				</td>
				<td>
					<%= @spectacle.address %>
				</td>
				<td>
					<%= @spectacle.date_start %>
				</td>					
				<td>
					<%= @spectacle.date_finish %>
				</td>	
				<td>
					<%= @spectacle.type_event %>
				</td>	
			</tr>
		</tbody>
	</table>
</div>